/* ============================================================
   Trilingual content dictionary (RU / EN / ZH).
   Mirrored shape. All visible strings live here.
   Source of truth: SCENARIO_V2.md (Section 7 copy table).
   ============================================================ */

window.SITE_CONTENT = {
  /* --------------------------------------------------------- RU */
  ru: {
    meta: {
      lang: "ru",
      ogLocale: "ru_RU",
      title:
        "Степан Турченко - внедрение ИИ, Senior Fullstack и Tech Lead",
      description:
        "Специалист по внедрению ИИ, Senior Fullstack инженер и Tech Lead. Внедряю ИИ в реальные процессы компаний и отвечаю за инженерию, которая держит продукты в продакшене в США, Европе и России.",
      skipLink: "Перейти к содержимому",
    },
    nav: {
      wordmark: "Степан Турченко",
      tagline: "вместо целой команды инженеров",
      links: [
        { id: "approach", label: "Подход" },
        { id: "stack", label: "Стек" },
        { id: "work", label: "Проекты" },
        { id: "about", label: "Обо мне" },
      ],
      cta: "Связаться",
      menuOpen: "Открыть меню",
      menuClose: "Закрыть меню",
    },
    hero: {
      eyebrow: "Внедрение AI · Fullstack Engineer · Техлид · Консультации",
      headlineBefore: "Я ",
      headlineAccent: "внедряю",
      headlineAccentMark: "underline",
      headlineMid: " AI в бизнес и ",
      headlineAccent2: "отвечаю",
      headlineAccent2Mark: "circle",
      headlineAfter: " за создание крутых айти продуктов с нуля",
      headlineSelect: "крутых",
      subtext:
        "Более 6 лет помогаю айти компаниям по всему миру достигать цели",
      ctaPrimary: "Смотреть работы",
      ctaSecondary: "Связаться",
    },
    infographic: {
      eyebrow: "Профит",
      axisX: "уровень автоматизации компании",
      axisY: "профит",
      steps: [
        { name: "Ручная работа", value: "×1" },
        { name: "Чат в окне", value: "×1.4" },
        { name: "Разрозненные агенты", value: "×2.1" },
        { name: "Общий контекст и обмен", value: "×2.8" },
      ],
      peak: { name: "Полная автоматизация ИТ-бизнеса", value: "×3.5", sub: "внедряет Степан Турченко" },
      alt: "Профит растёт вместе с уровнем автоматизации компании и выходит на полку при полной автоматизации ИТ-бизнеса",
    },
    proof: {
      leadBefore: "",
      leadAccent: "Результаты",
      leadAfter: " достигнуты",
      items: [
        { lead: "2 крупных продукта в США", qualifier: "выведены на рынок" },
        { lead: "8 средних бизнесов РФ", qualifier: "выведены на рынок" },
        { lead: "24 сайта и приложения", qualifier: "помогают предпринимателям" },
        { lead: "100+ агентов и обвязок", qualifier: "автоматизируют бизнес-процессы" },
      ],
    },
    approach: {
      index: "Внедрение ИИ",
      headlineBefore: "Привожу хаотичный ИИ к ",
      headlineAccent: "единой",
      headlineAfter: " системе в процессах компании.",
      lead: "Помогаю компаниям перейти от разрозненных промптов к общей среде, где агенты, контекст, правила и навыки переиспользуются всей командой.",
      map: {
        title: "Карта одной задачи",
        caption: "Один каркас на любую задачу: вход, разбор, изолированные субагенты, проверки, выход.",
        input: { label: "Задача из Slack", note: "тред, требования, ссылки" },
        main: { label: "Главный агент", note: "разбирает задачу и делегирует, сам код не пишет" },
        isolated: "изолированный контекст",
        agents: [
          { label: "Ресерч", note: "читает код и документы, приносит факты" },
          { label: "Правка кода", note: "вносит изменения в отдельной ветке" },
          { label: "Тесты", note: "прогоняет сценарии и чинит падения" },
          { label: "Отчёт", note: "сводит результат в готовый текст" },
        ],
        gate: { label: "Проверки", note: "линт · тесты · ревью" },
        output: { label: "Релиз и отчёт в Slack", note: "ссылка на изменения и короткий итог" },
        busTitle: "Общая шина: память (gbrain) · правила · навыки · форматы",
        bus: [
          { label: "Общая память (gbrain)", note: "проекты, решения и грабли живут между сессиями и людьми" },
          { label: "Правила и форматы", note: "как писать код, отчёты и сообщения - одинаково у всех" },
          { label: "Навыки", note: "способность, описанная текстом: пишется один раз и переиспользуется" },
        ],
      },
      runs: {
        title: "Прогон задачи по карте",
        caption: "Четыре процесса, которые уже идут по этому каркасу.",
        manualLabel: "вручную",
        agentLabel: "агентами",
        items: [
          {
            area: "Проджект",
            steps: ["тред в Slack", "разбор", "исполнитель и доска", "задача", "ссылка в тред"],
            manual: "40 мин", agent: "2 мин", manualMin: 40, agentMin: 2,
            before: "Вручную читать тред в Slack, выбирать исполнителя и заводить задачу.",
            after: "Агент читает тред, выбирает исполнителя, находит доску и колонку, создаёт задачу и возвращает ссылку.",
            more: "и десятки других примеров оптимизации работы отдела продукта",
          },
          {
            area: "Финансы",
            steps: ["чеки и списания", "сверка доходов", "таблица", "проверка", "пост в Slack"],
            manual: "3 ч", agent: "6 мин", manualMin: 180, agentMin: 6,
            before: "Вручную собирать чеки, сверять доходы и сводить таблицу.",
            after: "Агент собирает чеки и списания, сверяет доходы, строит таблицу и по расписанию публикует в Slack.",
            more: "и десятки других примеров оптимизации финансов и отчётности",
          },
          {
            area: "QA",
            steps: ["инструкция", "прогон фичи", "движение по колонкам", "баг-репорт", "вопрос о версии"],
            manual: "2 ч", agent: "12 мин", manualMin: 120, agentMin: 12,
            before: "Вручную проходить фичу по инструкции и писать баг-репорт.",
            after: "Агент тестирует фичу по инструкции, двигает задачу по колонкам, пишет баг-репорт и спрашивает версию, если её нет.",
            more: "и десятки других примеров оптимизации работы отдела QA",
          },
          {
            area: "Аналитика",
            steps: ["выгрузка из источников", "сборка цифр", "график", "что выросло и что упало", "пост в Slack"],
            manual: "1,5 ч", agent: "4 мин", manualMin: 90, agentMin: 4,
            before: "Вручную выгружать цифры из всех источников и искать, что изменилось.",
            after: "Агент собирает сырые цифры из всех источников, строит график и сразу пишет, что выросло и что упало, и по расписанию публикует в Slack.",
            more: "и десятки других примеров для аналитики, разработки и смежных команд",
          },
        ],
      },
      expandMore: "Развернуть подробнее",
      collapse: "Свернуть",
    },
    cases: {
      index: "Работы",
      sectionTitle: "Проекты и компании",
      headline: "Список моих проектов и компаний.",
      lead: "Компании, где я был не просто разработчиком: помогал выстраивать процессы, приносил идеи и отвечал за то, чтобы продукт рос. Звезда отмечает крупные проекты.",
      legend: "крупные проекты",
      legendMedium: "средняя сложность",
      photoNote: "я кайфую от своей работы",
      visit: "Открыть",
      items: [
        { title: "Painta", major: true, role: "Лид AI-продукта, fullstack (команда из 2)", oneline: "AI-коуч по рисованию целиком: приложение на React Native, backend на Supabase, платежи и N8N-автоматизации, живой и растёт.", tags: ["AI Product", "React Native", "Supabase", "N8N", "DevOps", "Payments"] },
        { title: "Aspect Health", major: true, role: "Fullstack и управление командой (команда из 5)", oneline: "Платформа women-health с AI-приложением: три года владел тремя тяжёлыми сервисами на Node.js и GCP и вёл QA на всю компанию.", tags: ["Node.js", "Nest.js", "GCP", "Microservices", "QA", "Team Lead"] },
        { title: "Nana800", major: true, role: "Основатель и технический лид", oneline: "Мой low-code продукт: визуальные сценарии, интеграции и AI-блоки превращают идеи в рабочие автоматизированные процессы.", tags: ["Founder", "Low-code", "AI", "Automation", "Integrations"] },
        { title: "Московский спорт", major: true, role: "Мобильный инженер", oneline: "Мобильное приложение городского спорта Москвы: участвовал в разработке как инженер.", tags: ["Gov", "React Native", "Mobile"] },
        { title: "Bismap", stars: 2, role: "Backend и мобильное (один разработчик)", oneline: "B2B-приложение для тендеров: регистрация бизнеса, заявки и весь backend, передано заказчику в самостоятельное управление.", tags: ["Nest.js", "React Native", "MongoDB", "B2B", "Backend"] },
        { title: "Stayfit", stars: 2, role: "Senior fullstack (React Native, Node.js)", oneline: "Корпоративное wellbeing-приложение: спорт-челленджи, онлайн-консультации, обучающий контент и соревнования команд.", tags: ["React Native", "Node.js", "GraphQL", "MongoDB", "Tech Lead"] },
        { title: "Bigam", role: "Мобильный инженер и тех-лид", oneline: "Retail-приложение сети строительных магазинов: каталог, фильтры, доставка, оплата в приложении и при получении, персональные цены и интеграции с 1С, выпущено в стор.", tags: ["React Native", "Node.js", "1C", "API", "DevOps"] },
        { title: "Small", role: "Мобильный инженер (тех-команда из 3)", oneline: "Приложение супермаркета без касс: покупки без очередей через сканирование QR и штрихкодов и оплату в приложении картой, Google Pay или Apple Pay.", tags: ["React Native", "Redux", "Payments", "Mobile"] },
        { title: "Liverpool", role: "Мобильный лид и тимлид", oneline: "Приложение доставки еды для сети ресторанов: меню, заказы, оплата Сбер и картой и трекинг доставки в реальном времени через веб-сокеты.", tags: ["React Native", "WebSockets", "Payments", "Tech Lead"] },
        { title: "GroupQ", role: "Мобильный инженер и backend", oneline: "Приложение лояльности для АЗС: бонусы, акции, цены на топливо, маршруты, интеграции с Yandex API и 1С.", tags: ["React Native", "Node.js", "Maps", "1C", "API"] },
        { title: "Ageeva Stom", role: "Веб (сайт клиники)", oneline: "Сайт частной стоматологии в Калининграде: доверие, услуги, запись и маршрут.", tags: ["Web", "Frontend", "Clinic"] },
        { title: "Solnechnaya Arka", role: "Веб (каталог)", oneline: "Витрина теплиц и садовых конструкций: каталог, преимущества, доставка и заявки.", tags: ["Web", "Frontend", "Catalog"] },
        { title: "ProFitness", role: "Веб (лендинг сети)", oneline: "Сайт сети фитнес-клубов на четыре локации: услуги и первый контакт с клиентом.", tags: ["Web", "Frontend", "Landing"] },
      ],
      credential: {
        text: "В каждый свой проект вкладываю душу и творчество.",
      },
    },
    stack: {
      index: "Стек",
      headline: "Что я использую.",
      note: "Свободно говорю по-английски",
      clusters: [
        { title: "ИИ и автоматизация", emphasis: true, chips: ["Claude Code", "AI Agents", "Prompt Engineering", "N8N", "Cursor", "AI workflow automation"] },
        { title: "Фронтенд и мобильное", chips: ["React", "React Native", "SPA", "TypeScript", "Zustand", "Expo"] },
        { title: "Backend и данные", chips: ["Node.js", "Nest.js", "Next.js", "PostgreSQL", "MongoDB", "Supabase", "Redis", "RabbitMQ", "Microservices"] },
        { title: "DevOps и облако", chips: ["Docker", "Dokploy", "CI/CD", "Google Cloud", "AWS", "Grafana", "Loki", "Nginx", "Traefik"] },
      ],
      management: {
        title: "Технический менеджмент",
        body: "Управляю разработкой и проектирую системы целиком: от архитектуры до релиза. Налаживаю процессы внутри компании и продукта, строю технический план развития и внедряю ИИ в рабочие процессы бизнеса, чтобы команда двигалась быстрее и предсказуемее.",
      },
      cert: "Сертификаты W3 по TypeScript и React.",
      hackathon: "Призёр хакатона 2022 года",
    },
    about: {
      index: "О себе",
      headline: "Обо мне",
      body: "Шестой год делаю продукты и собираю команды вокруг них. Три года вёл сервисы women-health стартапа в Делавэре, потом ритейл и B2B в России, сейчас мобильная разработка с агентами в Европе. Отвечаю за архитектуру, релизы и инфраструктуру, разбираю инциденты. Собеседования и переговоры веду на английском. Сейчас внедряю ИИ-агентов в работу компаний.",
      facts: "Веду небольшой личный блог про айти бизнес и разработку",
      interests: "Занимаюсь падел теннисом и немного боксом, владелец собаки, увлекаюсь экономикой и технологиями",
    },
    photos: {
      kicker: "Человек за работами",
      caption: "Степан Турченко",
    },
    contact: {
      index: "Контакт",
      headlineBefore: "Расскажите, что вы ",
      headlineAccent: "создаёте",
      headlineAfter: ".",
      subline: "и мы вместе построим стратегию развития вашего продукта.",
      cta: "Связаться",
      emailLabel: "Почта",
      phoneLabel: "Телефон",
    },
    footer: {
      name: "Степан Турченко",
      backToTop: "Наверх",
    },
  },

  /* --------------------------------------------------------- EN */
  en: {
    meta: {
      lang: "en",
      ogLocale: "en_US",
      title: "Stepan Turchenko - AI Integration Specialist, Senior Fullstack & Tech Lead",
      description:
        "AI Integration Specialist, Senior Fullstack engineer and Tech Lead. I bring AI into real business processes and own the engineering that keeps products running in production across the US, Europe and Russia.",
      skipLink: "Skip to content",
    },
    nav: {
      wordmark: "Stepan Turchenko",
      tagline: "instead of a whole engineering team",
      links: [
        { id: "approach", label: "Approach" },
        { id: "stack", label: "Stack" },
        { id: "work", label: "Projects" },
        { id: "about", label: "About" },
      ],
      cta: "Get in touch",
      menuOpen: "Open menu",
      menuClose: "Close menu",
    },
    hero: {
      eyebrow: "AI Integration · Fullstack Engineer · Tech Lead · Consulting",
      headlineBefore: "I ",
      headlineAccent: "integrate",
      headlineAccentMark: "underline",
      headlineMid: " AI into real business and ",
      headlineAccent2: "own",
      headlineAccent2Mark: "circle",
      headlineAfter: " the creation of strong IT products from scratch.",
      headlineSelect: "strong",
      subtext:
        "More than six years helping IT companies worldwide reach their goals",
      ctaPrimary: "See selected work",
      ctaSecondary: "Get in touch",
    },
    infographic: {
      eyebrow: "Profit",
      axisX: "company automation level",
      axisY: "profit",
      steps: [
        { name: "Manual work", value: "×1" },
        { name: "Chat in a window", value: "×1.4" },
        { name: "Scattered agents", value: "×2.1" },
        { name: "Shared context", value: "×2.8" },
      ],
      peak: { name: "Full IT business automation", value: "×3.5", sub: "implemented by Stepan Turchenko" },
      alt: "Profit grows with the company automation level and levels off at full IT business automation",
    },
    proof: {
      leadBefore: "",
      leadAccent: "Results",
      leadAfter: " delivered",
      items: [
        { lead: "2 large products in the USA", qualifier: "taken to market" },
        { lead: "8 mid-size businesses in Russia", qualifier: "taken to market" },
        { lead: "24 sites and apps", qualifier: "helping entrepreneurs" },
        { lead: "100+ agents and harnesses", qualifier: "automating business processes" },
      ],
    },
    approach: {
      index: "AI integration",
      headlineBefore: "I turn chaotic AI into one ",
      headlineAccent: "unified",
      headlineAfter: " system across a company's processes.",
      lead: "I move companies from scattered prompts to a shared environment where agents, context, rules, and skills are reused by the whole team.",
      map: {
        title: "Map of a single task",
        caption: "One frame for any task: input, breakdown, isolated subagents, checks, output.",
        input: { label: "Task from Slack", note: "thread, requirements, links" },
        main: { label: "Main agent", note: "breaks the task down and delegates, writes no code itself" },
        isolated: "isolated context",
        agents: [
          { label: "Research", note: "reads the code and the docs, brings back facts" },
          { label: "Code change", note: "makes the edits in a separate branch" },
          { label: "Tests", note: "runs the scenarios and fixes the failures" },
          { label: "Report", note: "turns the result into finished text" },
        ],
        gate: { label: "Checks", note: "lint · tests · review" },
        output: { label: "Release and report back to Slack", note: "link to the changes and a short summary" },
        busTitle: "Shared bus: memory (gbrain) · rules · skills · formats",
        bus: [
          { label: "Shared memory (gbrain)", note: "projects, decisions, and pitfalls live across sessions and people" },
          { label: "Rules and formats", note: "how code, reports, and messages are written - the same for everyone" },
          { label: "Skills", note: "a capability described in text: written once and reused" },
        ],
      },
      runs: {
        title: "A task running across the map",
        caption: "Four processes already running on this frame.",
        manualLabel: "by hand",
        agentLabel: "with agents",
        items: [
          {
            area: "PM",
            steps: ["Slack thread", "breakdown", "assignee and board", "task", "link back"],
            manual: "40 min", agent: "2 min", manualMin: 40, agentMin: 2,
            before: "Manually read a Slack thread, pick the assignee, and open a task.",
            after: "An agent reads the thread, picks the assignee, finds the board and column, creates the task, and posts the link back.",
            more: "and dozens more examples of product-team workflow optimization",
          },
          {
            area: "Finance",
            steps: ["receipts and charges", "income reconciliation", "table", "check", "post to Slack"],
            manual: "3 h", agent: "6 min", manualMin: 180, agentMin: 6,
            before: "Manually collect receipts, reconcile income, and assemble the table.",
            after: "An agent collects receipts and charges, reconciles income, builds the table, and posts to Slack on a schedule.",
            more: "and dozens more examples in finance and reporting",
          },
          {
            area: "QA",
            steps: ["instructions", "feature run", "moving across columns", "bug report", "version question"],
            manual: "2 h", agent: "12 min", manualMin: 120, agentMin: 12,
            before: "Manually walk a feature through its instructions and write the bug report.",
            after: "An agent tests the feature by the instructions, moves the task across columns, writes the bug report, and asks for the version if it is missing.",
            more: "and dozens more examples of QA workflow optimization",
          },
          {
            area: "Analytics",
            steps: ["pull from sources", "assemble numbers", "chart", "what rose and what fell", "post to Slack"],
            manual: "1.5 h", agent: "4 min", manualMin: 90, agentMin: 4,
            before: "Manually pull numbers from every source and hunt for what changed.",
            after: "An agent pulls raw numbers from all sources, builds a chart and flags what moved, and posts to Slack on a schedule.",
            more: "and dozens more for analytics, engineering, and adjacent teams",
          },
        ],
      },
      expandMore: "Show details",
      collapse: "Collapse",
    },
    cases: {
      index: "Work",
      sectionTitle: "Projects and companies",
      headline: "A list of my projects and companies.",
      lead: "Apps, platforms, and sites across AI, health, retail, sport, and B2B. The star marks major projects.",
      legend: "major projects",
      legendMedium: "medium complexity",
      photoNote: "I love the work I do",
      visit: "Open",
      items: [
        { title: "Painta", major: true, role: "AI product lead, fullstack (team of 2)", oneline: "An AI art coach end to end: React Native app, Supabase backend, payments, and N8N automations, live and growing.", tags: ["AI Product", "React Native", "Supabase", "N8N", "DevOps", "Payments"] },
        { title: "Aspect Health", major: true, role: "Fullstack and team management (team of 5)", oneline: "A women-health platform with an AI app: three years owning three heavy services on Node.js and GCP, plus company-wide QA.", tags: ["Node.js", "Nest.js", "GCP", "Microservices", "QA", "Team Lead"] },
        { title: "Nana800", major: true, role: "Founder and technical lead", oneline: "My own low-code product: visual scenarios, integrations, and AI blocks turn ideas into working automated processes.", tags: ["Founder", "Low-code", "AI", "Automation", "Integrations"] },
        { title: "Moscow Sport", major: true, role: "Mobile engineer", oneline: "Moscow city sport mobile app: worked on it as an engineer.", tags: ["Gov", "React Native", "Mobile"] },
        { title: "Bismap", stars: 2, role: "Backend and mobile (solo developer)", oneline: "A B2B tenders app: business registration, applications, and the full backend, then handed to the client to run.", tags: ["Nest.js", "React Native", "MongoDB", "B2B", "Backend"] },
        { title: "Stayfit", stars: 2, role: "Senior fullstack (React Native, Node.js)", oneline: "A corporate wellbeing app: sport challenges, online consultations, training content, and team competition.", tags: ["React Native", "Node.js", "GraphQL", "MongoDB", "Tech Lead"] },
        { title: "Bigam", role: "Mobile engineer and tech lead", oneline: "A hardware-store chain retail app: catalog, filters, delivery, in-app and on-delivery payment, personalized pricing, and 1C integrations, shipped to store.", tags: ["React Native", "Node.js", "1C", "API", "DevOps"] },
        { title: "Small", role: "Mobile engineer (tech team of 3)", oneline: "A cashier-free supermarket app: shop without checkout lines via QR and barcode scanning and in-app payment by card, Google Pay, or Apple Pay.", tags: ["React Native", "Redux", "Payments", "Mobile"] },
        { title: "Liverpool", role: "Mobile lead and team lead", oneline: "A food-delivery app for a restaurant chain: menu, ordering, Sber and card payments, and real-time delivery tracking over web sockets.", tags: ["React Native", "WebSockets", "Payments", "Tech Lead"] },
        { title: "GroupQ", role: "Mobile engineer and backend", oneline: "A fuel-station loyalty app: bonuses, promos, fuel prices, route maps, Yandex API and 1C integrations.", tags: ["React Native", "Node.js", "Maps", "1C", "API"] },
        { title: "Ageeva Stom", role: "Web (clinic site)", oneline: "A private dental clinic site in Kaliningrad: trust, services, booking, and directions.", tags: ["Web", "Frontend", "Clinic"] },
        { title: "Solnechnaya Arka", role: "Web (catalog store)", oneline: "A greenhouse and garden-structures storefront: catalog, benefits, delivery, and leads.", tags: ["Web", "Frontend", "Catalog"] },
        { title: "ProFitness", role: "Web (chain landing)", oneline: "A fitness-chain site across four locations: services and first client contact.", tags: ["Web", "Frontend", "Landing"] },
      ],
      credential: {
        text: "I put heart and craft into every project I take on.",
      },
    },
    stack: {
      index: "Stack",
      headline: "What I use.",
      note: "Fluent in English",
      clusters: [
        { title: "AI & Automation", emphasis: true, chips: ["Claude Code", "AI Agents", "Prompt Engineering", "N8N", "Cursor", "AI workflow automation"] },
        { title: "Frontend & Mobile", chips: ["React", "React Native", "SPA", "TypeScript", "Zustand", "Expo"] },
        { title: "Backend & Data", chips: ["Node.js", "Nest.js", "Next.js", "PostgreSQL", "MongoDB", "Supabase", "Redis", "RabbitMQ", "Microservices"] },
        { title: "DevOps & Cloud", chips: ["Docker", "Dokploy", "CI/CD", "Google Cloud", "AWS", "Grafana", "Loki", "Nginx", "Traefik"] },
      ],
      management: {
        title: "Technical management",
        body: "I run engineering and design whole systems end to end, from architecture to release. I set up the processes inside the company and the product, build the technical roadmap, and bring AI into business workflows so the team moves faster and more predictably.",
      },
      cert: "W3-certified in TypeScript and React.",
      hackathon: "Hackathon prize winner, 2022",
    },
    about: {
      index: "About",
      headline: "About",
      body: "Sixth year building products and the teams around them. Three years running the services of a women-health startup in Delaware, then retail and B2B in Russia, now agent-driven mobile work in Europe. I own architecture, releases and infrastructure, and I handle incidents. I interview and negotiate in English. Right now I bring AI agents into how companies work.",
      facts: "I keep a small personal blog about IT business and development",
      interests: "I play padel and box a little, own a dog, and follow economics and technology",
    },
    photos: {
      kicker: "The person behind the work",
      caption: "Stepan Turchenko",
    },
    contact: {
      index: "Contact",
      headlineBefore: "Let me know what you are ",
      headlineAccent: "creating",
      headlineAfter: ".",
      subline: "and together we'll build a growth strategy for your product.",
      cta: "Get in touch",
      emailLabel: "Email",
      phoneLabel: "Phone",
    },
    footer: {
      name: "Stepan Turchenko",
      backToTop: "Back to top",
    },
  },

  /* --------------------------------------------------------- ZH */
  zh: {
    meta: {
      lang: "zh",
      ogLocale: "zh_CN",
      title: "斯捷潘·图尔琴科 - AI 集成专家 / 高级全栈工程师 / 技术负责人",
      description:
        "AI 集成专家、高级全栈工程师与技术负责人。我把 AI 落地到企业真实的业务流程中，并负责支撑产品在美国、欧洲和俄罗斯稳定运行的整套工程。",
      skipLink: "跳到内容",
    },
    nav: {
      wordmark: "斯捷潘·图尔琴科",
      tagline: "一人顶一支工程团队",
      links: [
        { id: "approach", label: "方法" },
        { id: "stack", label: "技术栈" },
        { id: "work", label: "项目" },
        { id: "about", label: "关于" },
      ],
      cta: "联系我",
      menuOpen: "打开菜单",
      menuClose: "关闭菜单",
    },
    hero: {
      eyebrow: "AI 集成 · 全栈工程师 · 技术负责人 · 咨询",
      headlineBefore: "把 AI ",
      headlineAccent: "落地",
      headlineAccentMark: "underline",
      headlineMid: "到企业真实业务，并",
      headlineAccent2: "负责",
      headlineAccent2Mark: "circle",
      headlineAfter: "从零打造出色的 IT 产品。",
      headlineSelect: "出色的",
      subtext: "六年多帮助全球 IT 公司实现目标",
      ctaPrimary: "查看作品",
      ctaSecondary: "联系我",
    },
    infographic: {
      eyebrow: "利润",
      axisX: "企业自动化水平",
      axisY: "利润",
      steps: [
        { name: "手工作业", value: "×1" },
        { name: "只用聊天窗口", value: "×1.4" },
        { name: "各自为战的智能体", value: "×2.1" },
        { name: "共享上下文", value: "×2.8" },
      ],
      peak: { name: "IT 业务全面自动化", value: "×3.5", sub: "由 Stepan Turchenko 落地" },
      alt: "利润随企业自动化水平提升，并在 IT 业务全面自动化时趋于平台期",
    },
    proof: {
      leadBefore: "",
      leadAccent: "成果",
      leadAfter: "已达成",
      items: [
        { lead: "2 个美国大型产品", qualifier: "已推向市场" },
        { lead: "8 家俄罗斯中型企业", qualifier: "已推向市场" },
        { lead: "24 个网站与应用", qualifier: "帮助创业者" },
        { lead: "100+ 智能体与外围系统", qualifier: "自动化业务流程" },
      ],
    },
    approach: {
      index: "AI 集成",
      headlineBefore: "我把混乱的 AI 收敛成贯穿企业流程的",
      headlineAccent: "统一",
      headlineAfter: "系统。",
      lead: "我帮助企业从零散的提示词，走向一个共享的环境：智能体、上下文、规则和技能由整个团队复用。",
      map: {
        title: "一个任务的流转图",
        caption: "任何任务都走同一套骨架：输入、拆解、隔离的子智能体、校验、输出。",
        input: { label: "来自 Slack 的任务", note: "讨论串、需求、链接" },
        main: { label: "主智能体", note: "拆解任务并委派，本身不写代码" },
        isolated: "隔离的上下文",
        agents: [
          { label: "调研", note: "阅读代码与文档，带回事实" },
          { label: "改代码", note: "在独立分支上做修改" },
          { label: "测试", note: "跑通场景并修复失败用例" },
          { label: "报告", note: "把结果整理成可直接发出的文本" },
        ],
        gate: { label: "校验", note: "静态检查 · 测试 · 评审" },
        output: { label: "发布并把报告发回 Slack", note: "改动链接与简短结论" },
        busTitle: "共享总线：记忆 (gbrain) · 规则 · 技能 · 格式",
        bus: [
          { label: "共享记忆 (gbrain)", note: "项目、决策与踩过的坑，跨会话、跨成员保留下来" },
          { label: "规则与格式", note: "代码、报告和消息怎么写 - 所有人保持一致" },
          { label: "技能", note: "用文字描述的一种能力：只写一次便可复用" },
        ],
      },
      runs: {
        title: "任务在图上的一次流转",
        caption: "已经按这套骨架运行的四个流程。",
        manualLabel: "手动",
        agentLabel: "交给智能体",
        items: [
          {
            area: "项目管理",
            steps: ["Slack 讨论串", "拆解", "负责人与看板", "创建任务", "把链接发回"],
            manual: "40 分钟", agent: "2 分钟", manualMin: 40, agentMin: 2,
            before: "手动阅读 Slack 讨论串，挑选负责人并创建任务。",
            after: "智能体阅读讨论串，挑选负责人，找到看板和列，创建任务并把链接发回。",
            more: "还有几十个产品团队流程优化的类似例子",
          },
          {
            area: "财务",
            steps: ["票据与扣款", "核对收入", "生成表格", "复核", "发布到 Slack"],
            manual: "3 小时", agent: "6 分钟", manualMin: 180, agentMin: 6,
            before: "手动收集票据、核对收入并汇总表格。",
            after: "智能体收集票据与扣款，核对收入，生成表格，并按计划发布到 Slack。",
            more: "还有几十个财务与报表方向的类似例子",
          },
          {
            area: "QA",
            steps: ["测试说明", "走查功能", "在各列间移动", "缺陷报告", "追问版本"],
            manual: "2 小时", agent: "12 分钟", manualMin: 120, agentMin: 12,
            before: "手动按说明走查功能并撰写缺陷报告。",
            after: "智能体按说明测试功能，在各列之间移动任务，撰写缺陷报告，缺少版本时主动询问。",
            more: "还有几十个 QA 流程优化的类似例子",
          },
          {
            area: "数据分析",
            steps: ["从各源导出", "汇总数字", "生成图表", "涨了什么跌了什么", "发布到 Slack"],
            manual: "1.5 小时", agent: "4 分钟", manualMin: 90, agentMin: 4,
            before: "手动从各个来源导出数字，逐一排查变化。",
            after: "智能体从所有来源拉取原始数字，生成图表并直接标出哪些涨了、哪些跌了，并按计划发布到 Slack。",
            more: "还有几十个面向分析、开发及相关团队的类似例子",
          },
        ],
      },
      expandMore: "展开详情",
      collapse: "收起",
    },
    cases: {
      index: "作品",
      sectionTitle: "项目与公司",
      headline: "我参与的项目与公司清单。",
      lead: "涵盖 AI、健康、零售、体育与 B2B 的应用、平台和网站。星标代表重点项目。",
      legend: "重点项目",
      legendMedium: "中等复杂度",
      photoNote: "我热爱自己的工作",
      visit: "打开",
      items: [
        { title: "Painta", major: true, role: "AI 产品负责人，全栈（2 人团队）", oneline: "一款端到端打造的 AI 绘画教练：React Native 应用、Supabase 后端、支付与 N8N 自动化，已上线并持续增长。", tags: ["AI Product", "React Native", "Supabase", "N8N", "DevOps", "Payments"] },
        { title: "Aspect Health", major: true, role: "全栈与团队管理（5 人团队）", oneline: "一个带 AI 应用的女性健康平台：三年间端到端负责三个基于 Node.js 与 GCP 的高负载服务，并建立全公司 QA。", tags: ["Node.js", "Nest.js", "GCP", "Microservices", "QA", "Team Lead"] },
        { title: "Nana800", major: true, role: "创始人兼技术负责人", oneline: "我自己的低代码产品：可视化场景、集成与 AI 模块，把想法变成可运行的自动化流程。", tags: ["Founder", "Low-code", "AI", "Automation", "Integrations"] },
        { title: "莫斯科体育", major: true, role: "移动端工程师", oneline: "莫斯科城市体育移动应用：以工程师身份参与开发。", tags: ["Gov", "React Native", "Mobile"] },
        { title: "Bismap", stars: 2, role: "后端与移动端（独立开发）", oneline: "一款 B2B 招投标应用：企业注册、投标申请以及完整后端，随后交付给客户自主运营。", tags: ["Nest.js", "React Native", "MongoDB", "B2B", "Backend"] },
        { title: "Stayfit", stars: 2, role: "高级全栈 (React Native, Node.js)", oneline: "一款企业健康应用：运动挑战、在线咨询、训练内容与团队竞赛。", tags: ["React Native", "Node.js", "GraphQL", "MongoDB", "Tech Lead"] },
        { title: "Bigam", role: "移动工程师兼技术负责人", oneline: "一款建材连锁零售应用：商品目录、筛选、配送、应用内与货到付款、个性化定价以及 1C 集成，已上架商店。", tags: ["React Native", "Node.js", "1C", "API", "DevOps"] },
        { title: "Small", role: "移动工程师（3 人技术团队）", oneline: "一款无收银台超市应用：通过扫描二维码和条形码免排队购物，并支持应用内银行卡、Google Pay 或 Apple Pay 支付。", tags: ["React Native", "Redux", "Payments", "Mobile"] },
        { title: "Liverpool", role: "移动端负责人兼团队负责人", oneline: "一款连锁餐厅的外卖应用：菜单、下单、Sber 与银行卡支付，以及基于 WebSocket 的实时配送追踪。", tags: ["React Native", "WebSockets", "Payments", "Tech Lead"] },
        { title: "GroupQ", role: "移动工程师与后端", oneline: "一款加油站会员应用：积分、促销、油价、路线地图，以及 Yandex API 与 1C 集成。", tags: ["React Native", "Node.js", "Maps", "1C", "API"] },
        { title: "Ageeva Stom", role: "网站（诊所）", oneline: "加里宁格勒一家私立牙科诊所的网站：信任感、服务项目、预约与导航。", tags: ["Web", "Frontend", "Clinic"] },
        { title: "Solnechnaya Arka", role: "网站（商品目录）", oneline: "一个温室与花园结构的展示商店：商品目录、优势、配送与销售线索。", tags: ["Web", "Frontend", "Catalog"] },
        { title: "ProFitness", role: "网站（连锁落地页）", oneline: "一个覆盖四个门店的连锁健身网站：服务介绍与客户首次联系。", tags: ["Web", "Frontend", "Landing"] },
      ],
      credential: {
        text: "每个项目我都投入心血与创造力。",
      },
    },
    stack: {
      index: "技术栈",
      headline: "我使用什么。",
      note: "英语流利",
      clusters: [
        { title: "AI 与自动化", emphasis: true, chips: ["Claude Code", "AI Agents", "Prompt Engineering", "N8N", "Cursor", "AI workflow automation"] },
        { title: "前端与移动端", chips: ["React", "React Native", "SPA", "TypeScript", "Zustand", "Expo"] },
        { title: "后端与数据", chips: ["Node.js", "Nest.js", "Next.js", "PostgreSQL", "MongoDB", "Supabase", "Redis", "RabbitMQ", "Microservices"] },
        { title: "DevOps 与云", chips: ["Docker", "Dokploy", "CI/CD", "Google Cloud", "AWS", "Grafana", "Loki", "Nginx", "Traefik"] },
      ],
      management: {
        title: "技术管理",
        body: "我端到端地管理研发并设计整套系统，从架构一直到发布。我在公司和产品内部理顺流程，制定技术发展规划，并把 AI 落地到业务流程中，让团队推进得更快、更可预期。",
      },
      cert: "持有 W3 的 TypeScript 与 React 认证。",
      hackathon: "2022 年黑客松获奖者",
    },
    about: {
      index: "关于",
      headline: "关于",
      body: "第六年做产品，也带起围绕产品的团队。在特拉华州的女性健康初创公司做了三年服务端，之后是俄罗斯的零售与 B2B，现在在欧洲做带智能体的移动端。架构、发布和基础设施归我，故障也由我排查。面试和谈判用英语。眼下把 AI 智能体带进企业的日常工作。",
      facts: "我写一个关于 IT 业务与开发的小型个人博客",
      interests: "打匹克球，也练一点拳击，养狗，关注经济与技术",
    },
    photos: {
      kicker: "作品背后的人",
      caption: "斯捷潘·图尔琴科",
    },
    contact: {
      index: "联系",
      headlineBefore: "告诉我你在",
      headlineAccent: "创造",
      headlineAfter: "什么。",
      subline: "我们一起为你的产品制定发展战略。",
      cta: "联系我",
      emailLabel: "邮箱",
      phoneLabel: "电话",
    },
    footer: {
      name: "斯捷潘·图尔琴科",
      backToTop: "返回顶部",
    },
  },
};

/* ---- Language-independent data (channels, asset paths) ---- */
window.SITE_STATIC = {
  langs: [
    { code: "ru", label: "RU" },
    { code: "en", label: "EN" },
    { code: "zh", label: "ZH" },
  ],
  /* Real live URLs per project. Keyed by every localized title so the
     renderer can resolve a link regardless of the active language. */
  projectUrls: {
    Painta: "https://painta.io",
    "Aspect Health": "https://www.aspect-health.com",
    Nana800: "http://nana800.io",
    "Moscow Sport": "https://sport.mos.ru/",
    "Московский спорт": "https://sport.mos.ru/",
    莫斯科体育: "https://sport.mos.ru/",
    Bigam: "https://www.bigam.ru/",
    Small: "https://apps.apple.com/ru/app/small/id1535215720",
    Liverpool: "https://vk.com/lkcafe",
    Bismap: "https://bismap.net/",
    Stayfit: "https://stayfitt.ru/",
    GroupQ: "https://groupq-ural.ru/",
    "Ageeva Stom": "https://ageevastom.ru",
    "Solnechnaya Arka": "http://solnechnayaarka.ru",
    ProFitness: "https://pro-fitness-39.ru",
  },
  photos: [
    "./assets/photos/stepan-01.webp",
    "./assets/photos/stepan-02.webp",
    "./assets/photos/stepan-03.webp",
    "./assets/photos/stepan-04.webp",
  ],
  channels: [
    { kind: "email", labelKey: "emailLabel", value: "stepanstepan4@gmail.com", href: "mailto:stepanstepan4@gmail.com" },
    { kind: "phone", labelKey: "phoneLabel", value: "+7 962 263 98 09", href: "tel:+79622639809" },
    { kind: "linkedin", label: "LinkedIn", value: "linkedin.com/in/stepanturchenko", href: "https://www.linkedin.com/in/stepanturchenko" },
    { kind: "telegram", label: "Telegram", value: "t.me/Stepan_Turchenko", href: "https://t.me/Stepan_Turchenko" },
    { kind: "instagram", label: "Instagram", value: "@stepan_turchenko", href: "https://www.instagram.com/stepan_turchenko/" },
  ],
};
